include themes/jb-dark.conf

font_family JetBrainsMono Nerd Font
font_size 11.25
text_composition_strategy legacy

background_opacity 0.99
hide_window_decorations yes
startup_session startup.session

map f11 toggle_fullscreen
