git:
  diffRenderers:
    - command: delta --paging=never
      colorArg: always

gui:
  sidePanelWidth: 0.2
  theme:
    selectedLineBgColor: ['#2b405a']
    activeBorderColor: ['#7a9cc6']
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true

customCommands:
  - key: 'D'
    context: 'commits'
    command: "git log --pretty=format:'%h %ad | %s%d [%an]' --date=short -n 20"
    output: terminal
